# This file was generated by GoReleaser. DO NOT EDIT.
cask "deliverator" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "1f302e94579b46b053deaf8828797fb921b369cfed00e382628fc9e4f2ae7293"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c13b302df9cf1e4acce164b780fda5c496a5b3824dab3fe4a6137c2f5aa49c3"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0be9a1d777c0d9ca85762d7a1df47c85b1c3a16d9d0430368607565ec9c1757"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5387224ad671928a085a20a4028b61854b85ceef7694d4e23a606e616f0dea44"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "deliverator"
  desc "Non-custodial Hyperliquid execution + tracking CLI for autonomous LLM agents."
  homepage "https://deliverator.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deliverator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deliverator"]
    end
  end

  # No zap stanza required

end
