# This file was generated by GoReleaser. DO NOT EDIT.
cask "deliverator" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c3de5f72e15455a42b76c4973f5ccce1c3fe9912e2fe281731acafef06f86c0e"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a3d18766497169aff35cbc4c03bc6467cfd27799c9483b3067bab882d4b6d33"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3309774285a9d5995e23db7ac32dad61c84488728811f2fac3e1fa49fa1aa51"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8db98d744346aaa4f974f00d11434953841373be5a529e2d66636bcdd41e13b"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "deliverator"
  desc "Non-custodial Hyperliquid execution + tracking CLI for autonomous LLM agents."
  homepage "https://deliverator.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deliverator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deliverator"]
    end
  end

  # No zap stanza required

end
