# This file was generated by GoReleaser. DO NOT EDIT.
cask "deliverator" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "48ade56039864e4b9b654ce5b5c938464f9d4653773f5488d573fe6df05daf0e"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3eb2a563d7f15eab0732f4bc8b44e82ee2df7d92c060d29cd383da2570b360b4"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d6a260970c557673303e73b892e30e4563d388cfa1d62967a9b0b646da522f1"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9086bbd6f79327e76fcc22e1f83644aebad569f0161321545695ee236dfbbac2"
      url "https://github.com/erickuhn19/deliverator/releases/download/v#{version}/deliverator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "deliverator"
  desc "Non-custodial Hyperliquid execution + tracking CLI for autonomous LLM agents."
  homepage "https://deliverator.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deliverator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deliverator"]
    end
  end

  # No zap stanza required

end
